# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Metasploit
baseurl: "/metasploit-framework"
url: ""

permalink: pretty

aux_links:
  "Metasploit Framework on GitHub":
    - "//github.com/rapid7/metasploit-framework"

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/rapid7/metasploit-framework"
gh_edit_branch: "master"
gh_edit_source: docs
gh_edit_view_mode: "tree"

#ga_tracking: UA-2709176-10
#ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

# Build settings
theme: just-the-docs
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

back_to_top: true
back_to_top_text: "Back to top"

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
  ignore:
    envs: development

exclude: [api]
